name: ZaramaFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 2.1
description: Plugin for the Zarama Freedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Alex33856, nooneelse]

# plugin.yml is no longer used to define commands.
